name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt update && sudo apt install g++ -y

      - name: Compile
        run: g++ calculator.cpp -o calculator

      - name: Run program
        run: ./calculator
